title: Jackie Halpern Quilts
description: "My hobby and passion is making quilts!  I am a self taught quilter
  and have made more than 110 quilts since 1997. "
profile_image: /static/img/screen-shot-2022-01-20-at-10.15.17-pm.png
